/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMenuForm;

import PackMenuForm.MesPanel.AjouterClient;
import PackMenuForm.MesPanel.AjouterReserv;
import PackMenuForm.MesPanel.ListeClient;
import PackMenuForm.MesPanel.ListeReserv;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author StongKa
 */
public class MenuReserv extends javax.swing.JInternalFrame {

    GridBagLayout layout = new GridBagLayout();
    AjouterReserv ar;
    ListeReserv lr;
    GridBagConstraints c;

    private void DynamicPanel(){
        DynamicGReserv.setLayout(layout);
        ar = new AjouterReserv();
        lr = new ListeReserv();
        c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicGReserv.add(ar,c);
        DynamicGReserv.add(lr,c);
        ar.setVisible(true);
        lr.setVisible(false); 
    }
    public MenuReserv() {
        initComponents();
        DynamicPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContentReserv = new javax.swing.JPanel();
        PanelBoutonReserv = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAjouterResrv = new javax.swing.JButton();
        btnListeReserv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DynamicGReserv = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        PanelBoutonReserv.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Réservations <<");
        jLabel1.setOpaque(true);

        btnAjouterResrv.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAjouterResrv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/AjoutReserv.png"))); // NOI18N
        btnAjouterResrv.setText("Nouvelle réservation");
        btnAjouterResrv.setContentAreaFilled(false);
        btnAjouterResrv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjouterResrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterResrvActionPerformed(evt);
            }
        });

        btnListeReserv.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnListeReserv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/listeVoiture.png"))); // NOI18N
        btnListeReserv.setText("Liste des réservations");
        btnListeReserv.setContentAreaFilled(false);
        btnListeReserv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListeReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeReservActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/Reservation.png"))); // NOI18N

        javax.swing.GroupLayout PanelBoutonReservLayout = new javax.swing.GroupLayout(PanelBoutonReserv);
        PanelBoutonReserv.setLayout(PanelBoutonReservLayout);
        PanelBoutonReservLayout.setHorizontalGroup(
            PanelBoutonReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBoutonReservLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBoutonReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAjouterResrv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListeReserv, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBoutonReservLayout.setVerticalGroup(
            PanelBoutonReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoutonReservLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnAjouterResrv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnListeReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DynamicGReserv.setBackground(new java.awt.Color(244, 243, 243));
        DynamicGReserv.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout DynamicGReservLayout = new javax.swing.GroupLayout(DynamicGReserv);
        DynamicGReserv.setLayout(DynamicGReservLayout);
        DynamicGReservLayout.setHorizontalGroup(
            DynamicGReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        DynamicGReservLayout.setVerticalGroup(
            DynamicGReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelContentReservLayout = new javax.swing.GroupLayout(PanelContentReserv);
        PanelContentReserv.setLayout(PanelContentReservLayout);
        PanelContentReservLayout.setHorizontalGroup(
            PanelContentReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContentReservLayout.createSequentialGroup()
                .addComponent(PanelBoutonReserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DynamicGReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelContentReservLayout.setVerticalGroup(
            PanelContentReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBoutonReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContentReservLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicGReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContentReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContentReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterResrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterResrvActionPerformed
        // TODO add your handling code here:
        ar.setVisible(true);
        lr.setVisible(false); 
    }//GEN-LAST:event_btnAjouterResrvActionPerformed

    private void btnListeReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeReservActionPerformed
        // TODO add your handling code here:
        ar.setVisible(false);
        lr.setVisible(true); 
    }//GEN-LAST:event_btnListeReservActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicGReserv;
    private javax.swing.JPanel PanelBoutonReserv;
    private javax.swing.JPanel PanelContentReserv;
    private javax.swing.JButton btnAjouterResrv;
    private javax.swing.JButton btnListeReserv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
