/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMenuForm;

import PackMenuForm.MesPanel.AjouterClient;
import PackMenuForm.MesPanel.AjouterVehi;
import PackMenuForm.MesPanel.ListeClient;
import PackMenuForm.MesPanel.ListeVehi;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author StongKa
 */
public class MenuVehi extends javax.swing.JInternalFrame {

    GridBagLayout layout = new GridBagLayout();
    AjouterVehi av;
    ListeVehi lv;
    GridBagConstraints c;

    private void DynamicPanel(){
        DynamicGReserv.setLayout(layout);
        av = new AjouterVehi();
        lv = new ListeVehi();
        c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicGReserv.add(av,c);
        DynamicGReserv.add(lv,c);
        av.setVisible(true);
        lv.setVisible(false);    
    }
    public MenuVehi() {
        initComponents();
        DynamicPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContentVehi = new javax.swing.JPanel();
        PanelBoutonVehi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAjouterVehi = new javax.swing.JButton();
        btnListeVehi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DynamicGReserv = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        PanelBoutonVehi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des Véhicules <<");
        jLabel1.setOpaque(true);

        btnAjouterVehi.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAjouterVehi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/AjoutVoiture.png"))); // NOI18N
        btnAjouterVehi.setText("Ajouter une véhicules");
        btnAjouterVehi.setContentAreaFilled(false);
        btnAjouterVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjouterVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterVehiActionPerformed(evt);
            }
        });

        btnListeVehi.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnListeVehi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/listeVoiture.png"))); // NOI18N
        btnListeVehi.setText("Liste des véhicules");
        btnListeVehi.setContentAreaFilled(false);
        btnListeVehi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListeVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeVehiActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/Voitures.png"))); // NOI18N

        javax.swing.GroupLayout PanelBoutonVehiLayout = new javax.swing.GroupLayout(PanelBoutonVehi);
        PanelBoutonVehi.setLayout(PanelBoutonVehiLayout);
        PanelBoutonVehiLayout.setHorizontalGroup(
            PanelBoutonVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBoutonVehiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBoutonVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAjouterVehi, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnListeVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBoutonVehiLayout.setVerticalGroup(
            PanelBoutonVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBoutonVehiLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnAjouterVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnListeVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        DynamicGReserv.setBackground(new java.awt.Color(244, 243, 243));
        DynamicGReserv.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout DynamicGReservLayout = new javax.swing.GroupLayout(DynamicGReserv);
        DynamicGReserv.setLayout(DynamicGReservLayout);
        DynamicGReservLayout.setHorizontalGroup(
            DynamicGReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        DynamicGReservLayout.setVerticalGroup(
            DynamicGReservLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelContentVehiLayout = new javax.swing.GroupLayout(PanelContentVehi);
        PanelContentVehi.setLayout(PanelContentVehiLayout);
        PanelContentVehiLayout.setHorizontalGroup(
            PanelContentVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContentVehiLayout.createSequentialGroup()
                .addComponent(PanelBoutonVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DynamicGReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelContentVehiLayout.setVerticalGroup(
            PanelContentVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBoutonVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContentVehiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicGReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContentVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContentVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterVehiActionPerformed
        // TODO add your handling code here:
        av.setVisible(true);
        lv.setVisible(false);
    }//GEN-LAST:event_btnAjouterVehiActionPerformed

    private void btnListeVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeVehiActionPerformed
        // TODO add your handling code here:
        av.setVisible(false);
        lv.setVisible(true);
    }//GEN-LAST:event_btnListeVehiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicGReserv;
    private javax.swing.JPanel PanelBoutonVehi;
    private javax.swing.JPanel PanelContentVehi;
    private javax.swing.JButton btnAjouterVehi;
    private javax.swing.JButton btnListeVehi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
