/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMenuForm;

import java.awt.Desktop;

public class MenuForm extends javax.swing.JFrame {
    MenuClient mac;
    MenuVehi mav;
    MenuReserv mar;
    MenuLoca mal;
    private void AfficheFrameClient(){
        mac = new MenuClient();
        Desktop.add(mac);
        mac.setVisible(true);
    }
    
    public void AfficheMenu(){
        if(MenuBarFichier.isEnabled()){
           MenuBarFichier.setEnabled(false); 
        }else{
           MenuBarFichier.setEnabled(true);  
        }
    }
    
    private void MenuDisable(){
        MenuBarFichier.setEnabled(false);
    }
    
    private void AfficheFrameVehi(){
        mav = new MenuVehi();
        Desktop.add(mav);
        mav.setVisible(true);
    }
    private void AfficheFrameReserv(){
        mar = new MenuReserv();
        Desktop.add(mar);
        mar.setVisible(true);
    }
    private void AfficheFrameLoca(){
        mal = new MenuLoca();
        Desktop.add(mal);
        mal.setVisible(true);
    }
  
    public MenuForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        MenuBarDesktop = new javax.swing.JMenuBar();
        MenuBarFichier = new javax.swing.JMenu();
        MenuGClients = new javax.swing.JMenu();
        MenuItemAjoutClient = new javax.swing.JMenuItem();
        MenuItemListeClients = new javax.swing.JMenuItem();
        MenuGVehi = new javax.swing.JMenu();
        MenuItemAjoutVehi = new javax.swing.JMenuItem();
        MenuItemListeVehi = new javax.swing.JMenuItem();
        MenuGReserv = new javax.swing.JMenu();
        MenuItemNouvelResrv = new javax.swing.JMenuItem();
        MenuItemListeReserv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion location des voitures");
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1440, 855));

        Desktop.setToolTipText("");
        Desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/TEST2.png"))); // NOI18N

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
                .addContainerGap())
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
        );
        Desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MenuBarDesktop.setPreferredSize(new java.awt.Dimension(56, 24));

        MenuBarFichier.setText("Fichier");

        MenuGClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/gestion des client.png"))); // NOI18N
        MenuGClients.setText("Gestion des clients");

        MenuItemAjoutClient.setText("Ajouter un client");
        MenuItemAjoutClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAjoutClientActionPerformed(evt);
            }
        });
        MenuGClients.add(MenuItemAjoutClient);

        MenuItemListeClients.setText("Liste des clients");
        MenuItemListeClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeClientsActionPerformed(evt);
            }
        });
        MenuGClients.add(MenuItemListeClients);

        MenuBarFichier.add(MenuGClients);

        MenuGVehi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/gestion véhicules.png"))); // NOI18N
        MenuGVehi.setText("Gestion des  véhicules");

        MenuItemAjoutVehi.setText("Ajouter une véhicules");
        MenuItemAjoutVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAjoutVehiActionPerformed(evt);
            }
        });
        MenuGVehi.add(MenuItemAjoutVehi);

        MenuItemListeVehi.setText("Liste des véhicules");
        MenuItemListeVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeVehiActionPerformed(evt);
            }
        });
        MenuGVehi.add(MenuItemListeVehi);

        MenuBarFichier.add(MenuGVehi);

        MenuGReserv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/gestion reservation.png"))); // NOI18N
        MenuGReserv.setText("Réservations");

        MenuItemNouvelResrv.setText("Nouvelle réservation");
        MenuItemNouvelResrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNouvelResrvActionPerformed(evt);
            }
        });
        MenuGReserv.add(MenuItemNouvelResrv);

        MenuItemListeReserv.setText("Liste des réservation");
        MenuItemListeReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeReservActionPerformed(evt);
            }
        });
        MenuGReserv.add(MenuItemListeReserv);

        MenuBarFichier.add(MenuGReserv);

        MenuBarDesktop.add(MenuBarFichier);

        setJMenuBar(MenuBarDesktop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAjoutClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAjoutClientActionPerformed
        // TODO add your handling code here:
        AfficheFrameClient();
        
        
    }//GEN-LAST:event_MenuItemAjoutClientActionPerformed

    private void MenuItemAjoutVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAjoutVehiActionPerformed
        // TODO add your handling code here:
        AfficheFrameVehi();
    }//GEN-LAST:event_MenuItemAjoutVehiActionPerformed

    private void MenuItemListeClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeClientsActionPerformed
        // TODO add your handling code here:
        AfficheFrameClient();
    }//GEN-LAST:event_MenuItemListeClientsActionPerformed

    private void MenuItemListeVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeVehiActionPerformed
        // TODO add your handling code here:
        AfficheFrameVehi();
    }//GEN-LAST:event_MenuItemListeVehiActionPerformed

    private void MenuItemNouvelResrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNouvelResrvActionPerformed
        // TODO add your handling code here:
        AfficheFrameReserv();
    }//GEN-LAST:event_MenuItemNouvelResrvActionPerformed

    private void MenuItemListeReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeReservActionPerformed
        // TODO add your handling code here:
        AfficheFrameReserv();
    }//GEN-LAST:event_MenuItemListeReservActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar MenuBarDesktop;
    private javax.swing.JMenu MenuBarFichier;
    private javax.swing.JMenu MenuGClients;
    private javax.swing.JMenu MenuGReserv;
    private javax.swing.JMenu MenuGVehi;
    private javax.swing.JMenuItem MenuItemAjoutClient;
    private javax.swing.JMenuItem MenuItemAjoutVehi;
    private javax.swing.JMenuItem MenuItemListeClients;
    private javax.swing.JMenuItem MenuItemListeReserv;
    private javax.swing.JMenuItem MenuItemListeVehi;
    private javax.swing.JMenuItem MenuItemNouvelResrv;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
