/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMenuForm.MesPanel;

import Application.BDD;
import Application.Parameter;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author StongKa
 */
public class AjouterReserv extends javax.swing.JPanel {

    ResultSet rs;
    BDD db;
    
    private void MontantPaiement(){
        txt_Montant.setText("1000,00");
    }
    
    private void Panel_BanqueReserv(){
        Panel_Banque.setVisible(false);
        if(rbtn_cheque.isSelected() || rbtn_carte.isSelected()){
            Panel_Banque.setVisible(true);
        }
    }
    
    private void GroupeBtnReserv(){
        GroupeBtn.add(rbtn_espece);
        GroupeBtn.add(rbtn_cheque);
        GroupeBtn.add(rbtn_carte);
    }
    
    private void DateDreserv(){
        String d=String.valueOf(JCalendarD.getDate());
        String f=String.valueOf(JCalendarF.getDate());
        txt_F_Reserv.setText(f);
        txt_D_Reserv.setText(d);  
    }
    
    private void InsertCmbNPiece(){
        String t[] = {"numPiece"};
        rs = db.querySelect(t ,"g_client_inf");
        try{
            
            while(rs.next()){
                cmb_piece.addItem(rs.getString("numPiece"));
                }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }
    
    private void InsertCmbModele(){
        String t[] = {"Modele"};
        rs = db.querySelect(t ,"g_client_vehi");
        try{
            
            while(rs.next()){
                cmb_Modele.addItem(rs.getString("Modele"));
                }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }
    
    private void FilterInfClient(){
        String nomPrenom;
        String t[] = {"nom", "prenom", "date_delivr_piece"};
        rs = db.fcSelectCommand(t ,"g_client_inf", " numPiece ='"+ cmb_piece.getSelectedItem().toString() + "'" );
        try{
            while(rs.next()){
                nomPrenom = rs.getString("nom");
                nomPrenom = rs.getString("prenom") +" "+ nomPrenom;
                txt_NomC.setText(nomPrenom);
                txt_dat_delivr_piece.setText(rs.getString("date_delivr_piece"));
                }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    private void FilterInfVehi(){
        
        String t[] = {"immatricule", "Marque"};
        rs = db.fcSelectCommand(t ,"g_client_vehi", " Modele ='"+ cmb_Modele.getSelectedItem().toString() + "'" );
        try{
            while(rs.next()){
                txt_Marque.setText(rs.getString("Marque"));
                txt_imma.setText(rs.getString("immatricule"));
                }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    private void actualser(){
        cmb_piece.setSelectedIndex(0);
        cmb_Modele.setSelectedIndex(0);
        txt_Marque.setText("");
        cmb_lieuD.setSelectedIndex(0);
        cmb_lieuF.setSelectedIndex(0);
        txt_dat_delivr_piece.setText("");
        txt_imma.setText("");
        txt_D_Reserv.setText("");
        txt_F_Reserv.setText("");
        txt_NomC.setText("");
        txt_Montant.setText("");
        txt_nmBanq.setText("");
        txt_numCarte.setText("");
    }
    private void MenuFonction(){
        MontantPaiement();
        Panel_BanqueReserv();
        InsertCmbNPiece();
        InsertCmbModele();
        GroupeBtnReserv();
    }
    public AjouterReserv() {
        initComponents();
        db =new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        MenuFonction();
        MontantPaiement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupeBtn = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnNouv = new javax.swing.JButton();
        btnAjout = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnImp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmb_piece = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_dat_delivr_piece = new javax.swing.JTextField();
        txt_NomC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_Modele = new javax.swing.JComboBox();
        txt_imma = new javax.swing.JTextField();
        txt_Marque = new javax.swing.JTextField();
        TabbedPanel = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_D_Reserv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_lieuD = new javax.swing.JComboBox();
        JCalendarD = new com.toedter.calendar.JCalendar();
        jPanel7 = new javax.swing.JPanel();
        txt_F_Reserv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmb_lieuF = new javax.swing.JComboBox();
        JCalendarF = new com.toedter.calendar.JCalendar();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Montant = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rbtn_espece = new javax.swing.JRadioButton();
        rbtn_cheque = new javax.swing.JRadioButton();
        rbtn_carte = new javax.swing.JRadioButton();
        Panel_Banque = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_nmBanq = new javax.swing.JTextField();
        txt_numCarte = new javax.swing.JTextField();

        setBackground(new java.awt.Color(244, 243, 243));

        jPanel2.setBackground(new java.awt.Color(244, 243, 243));

        jPanel6.setBackground(new java.awt.Color(244, 243, 243));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNouv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNouv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/nouveau.png"))); // NOI18N
        btnNouv.setText("Nouveau");
        btnNouv.setOpaque(false);
        btnNouv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouvActionPerformed(evt);
            }
        });

        btnAjout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAjout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/ENGR.png"))); // NOI18N
        btnAjout.setText("Enregistrer");
        btnAjout.setOpaque(false);
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/supprimer.png"))); // NOI18N
        btnSupp.setText("Supprimer");
        btnSupp.setEnabled(false);
        btnSupp.setFocusPainted(false);
        btnSupp.setOpaque(false);
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnImp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/Imprimer.png"))); // NOI18N
        btnImp.setText("Imprimer");
        btnImp.setEnabled(false);
        btnImp.setFocusPainted(false);
        btnImp.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(btnNouv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnNouv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/AjoutReserv.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Ajouter une réservation");

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(244, 243, 243));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Information client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("N° Pièce *");

        cmb_piece.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmb_piece.setOpaque(false);
        cmb_piece.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_pieceItemStateChanged(evt);
            }
        });
        cmb_piece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pieceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nom complete");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Date délivrance ");

        txt_dat_delivr_piece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dat_delivr_pieceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_NomC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmb_piece, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txt_dat_delivr_piece, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmb_piece, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_dat_delivr_piece, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_NomC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(244, 243, 243));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informations véhicule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modèle");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Marque");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Immatriculation *");

        cmb_Modele.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmb_Modele.setOpaque(false);
        cmb_Modele.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ModeleItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_Modele, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Marque, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_Modele, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Marque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TabbedPanel.setBackground(new java.awt.Color(244, 243, 243));
        TabbedPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabbedPanel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(244, 243, 243));

        jLabel3.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel3.setText("Date complet début réservation *");

        jLabel4.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel4.setText("Lieu départ *");

        cmb_lieuD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_lieuD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agence A", "Agence B" }));

        JCalendarD.setBackground(new java.awt.Color(244, 243, 243));
        JCalendarD.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                JCalendarDComponentAdded(evt);
            }
        });
        JCalendarD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JCalendarDAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JCalendarD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCalendarDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCalendarDMouseEntered(evt);
            }
        });
        JCalendarD.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                JCalendarDCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        JCalendarD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCalendarDKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txt_D_Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_lieuD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(JCalendarD, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_D_Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_lieuD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCalendarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPanel.addTab("Date et heure départ", jPanel5);

        jPanel7.setBackground(new java.awt.Color(244, 243, 243));

        jLabel11.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel11.setText("Date complet retour réservation *");

        jLabel12.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel12.setText("Lieu retour *");

        cmb_lieuF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_lieuF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agence X", "Agence Y" }));

        JCalendarF.setBackground(new java.awt.Color(244, 243, 243));
        JCalendarF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCalendarFMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JCalendarFMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_lieuF, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_F_Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JCalendarF, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_F_Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_lieuF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCalendarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPanel.addTab("Date et heure retour prévue", jPanel7);

        jPanel8.setBackground(new java.awt.Color(244, 243, 243));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Montant de cautionnement");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Mode de paiement");

        txt_Montant.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 0));
        jLabel17.setText("DH");

        rbtn_espece.setBackground(new java.awt.Color(244, 243, 243));
        rbtn_espece.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtn_espece.setText("Espèce");
        rbtn_espece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_especeActionPerformed(evt);
            }
        });

        rbtn_cheque.setBackground(new java.awt.Color(244, 243, 243));
        rbtn_cheque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtn_cheque.setText("Chèque");
        rbtn_cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_chequeActionPerformed(evt);
            }
        });

        rbtn_carte.setBackground(new java.awt.Color(244, 243, 243));
        rbtn_carte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtn_carte.setText("Carte credit");
        rbtn_carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_carteActionPerformed(evt);
            }
        });

        Panel_Banque.setBackground(new java.awt.Color(244, 243, 243));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Nom de la banque");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("N° de la carte");

        javax.swing.GroupLayout Panel_BanqueLayout = new javax.swing.GroupLayout(Panel_Banque);
        Panel_Banque.setLayout(Panel_BanqueLayout);
        Panel_BanqueLayout.setHorizontalGroup(
            Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BanqueLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nmBanq, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Panel_BanqueLayout.setVerticalGroup(
            Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BanqueLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_nmBanq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(Panel_BanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_numCarte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Montant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_espece)
                            .addComponent(rbtn_carte)
                            .addComponent(rbtn_cheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(Panel_Banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txt_Montant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rbtn_espece))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn_cheque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn_carte)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(Panel_Banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        TabbedPanel.addTab("Caution de la location", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabbedPanel))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouvActionPerformed
        // TODO add your handling code here:
           actualser();
    }//GEN-LAST:event_btnNouvActionPerformed

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        // TODO add your handling code here:
     if(txt_imma.getText().equals("") || txt_D_Reserv.getText().equals("") || txt_F_Reserv.getText().equals("")){

            JOptionPane.showMessageDialog(this, "SVP les champs avec (*) sont obligatoires ");
        }else {
         String b="";
            if(rbtn_espece.isSelected()){
                b ="Espèce";
            }else if(rbtn_cheque.isSelected()){
                b ="Chèque";
            }else if(rbtn_carte.isSelected()){
                b ="Carte credit";
            }
            String[] col = {"numPiece", "immatricule", "Date_depart", "Lieu_depart", "Date_retour", "Lieu_retour", "Montant", "Mode_paiement"};
            String[] inf = {cmb_piece.getSelectedItem().toString(), txt_imma.getText(), txt_D_Reserv.getText(),
                cmb_lieuD.getSelectedItem().toString(), txt_F_Reserv.getText(), cmb_lieuF.getSelectedItem().toString(), txt_Montant.getText(), b};
            try{
                System.out.println(db.queryInsert("g_reservation", col, inf));
                JOptionPane.showMessageDialog(this, "Enregistrer avec succée ");
            }catch(Exception e){
                System.out.println(e.getMessage());
                System.out.println("L ajoute du client n est pas valider");
            }
        }
    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppActionPerformed

    private void JCalendarDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JCalendarDAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarDAncestorAdded

    private void JCalendarDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalendarDMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarDMouseClicked

    private void JCalendarDCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JCalendarDCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarDCaretPositionChanged

    private void JCalendarDComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JCalendarDComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarDComponentAdded

    private void JCalendarDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCalendarDKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarDKeyPressed

    private void JCalendarDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalendarDMouseEntered
        // TODO add your handling code here:
        DateDreserv();
    }//GEN-LAST:event_JCalendarDMouseEntered

    private void JCalendarFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalendarFMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCalendarFMousePressed

    private void JCalendarFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalendarFMouseEntered
        // TODO add your handling code here:
        DateDreserv();
    }//GEN-LAST:event_JCalendarFMouseEntered

    private void cmb_pieceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_pieceItemStateChanged

        FilterInfClient();
    }//GEN-LAST:event_cmb_pieceItemStateChanged

    private void cmb_pieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pieceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_pieceActionPerformed

    private void cmb_ModeleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ModeleItemStateChanged
        // TODO add your handling code here:
        FilterInfVehi();
    }//GEN-LAST:event_cmb_ModeleItemStateChanged

    private void txt_dat_delivr_pieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dat_delivr_pieceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dat_delivr_pieceActionPerformed

    private void rbtn_chequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_chequeActionPerformed
        // TODO add your handling code here:
        Panel_BanqueReserv();
    }//GEN-LAST:event_rbtn_chequeActionPerformed

    private void rbtn_carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_carteActionPerformed
        // TODO add your handling code here:
        Panel_BanqueReserv();
    }//GEN-LAST:event_rbtn_carteActionPerformed

    private void rbtn_especeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_especeActionPerformed
        // TODO add your handling code here:
        Panel_Banque.setVisible(false);
        
    }//GEN-LAST:event_rbtn_especeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupeBtn;
    private com.toedter.calendar.JCalendar JCalendarD;
    private com.toedter.calendar.JCalendar JCalendarF;
    private javax.swing.JPanel Panel_Banque;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton btnImp;
    private javax.swing.JButton btnNouv;
    private javax.swing.JButton btnSupp;
    private javax.swing.JComboBox cmb_Modele;
    private javax.swing.JComboBox cmb_lieuD;
    private javax.swing.JComboBox cmb_lieuF;
    private javax.swing.JComboBox cmb_piece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton rbtn_carte;
    private javax.swing.JRadioButton rbtn_cheque;
    private javax.swing.JRadioButton rbtn_espece;
    private javax.swing.JTextField txt_D_Reserv;
    private javax.swing.JTextField txt_F_Reserv;
    private javax.swing.JTextField txt_Marque;
    private javax.swing.JTextField txt_Montant;
    private javax.swing.JTextField txt_NomC;
    private javax.swing.JTextField txt_dat_delivr_piece;
    private javax.swing.JTextField txt_imma;
    private javax.swing.JTextField txt_nmBanq;
    private javax.swing.JTextField txt_numCarte;
    // End of variables declaration//GEN-END:variables
}
