/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMenuForm.MesPanel;

import Application.BDD;
import Application.Parameter;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author StongKa
 */
public class AjouterVehi extends javax.swing.JPanel {

    ResultSet rs;
    BDD db;
    
//    private void InsertCmbMarque(){
//        String t[] = {"DISTINCT MarqueV"};
//        rs = db.querySelect(t ,"typevoitures");
//        try{
//            while(rs.next()){
//                cmb_marq.addItem(rs.getString("MarqueV"));
//                }
//        }catch(SQLException ex){
//            System.out.println(ex.getMessage());
//        } 
//    }
    private void InsertCmbModele(){
        String t[] = {"ModeleV"};
        rs = db.fcSelectCommand(t ,"typevoitures", " MarqueV ='"+ cmb_marq.getSelectedItem().toString() + "'" );
        try{
            cmb_mod.removeAllItems();
            while(rs.next()){
                cmb_mod.addItem(rs.getString("ModeleV"));
                }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    
    public void GroupBtn(){
        btnGroup.add(rbtn_ess);
        btnGroup.add(rbtn_gas);
        btnGroup.add(rbtn_gpl);
    }
    
    private void actualiser(){
        txt_imma.setText("");
        cmb_marq.setSelectedIndex(0);
        txt_nbr_plac.setText("");
        txt_puiss.setText("");
        date_circul.setDate(null);
        cmb_lieu_stat.setSelectedIndex(0);                                  
        txt_num_chass.setText("");
        txt_cod_rad.setText("");
        cmb_cate.setSelectedIndex(0);                    
        cmb_coul.setSelectedIndex(0);
        txt_delai_deb.setDate(null);
        txt_delai_fin.setDate(null);
    }
    
    public AjouterVehi() {
        initComponents();
        db =new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        GroupBtn();
        //InsertCmbMarque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnNouv = new javax.swing.JButton();
        btnAjout = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnImp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmb_lieu_stat = new javax.swing.JComboBox();
        cmb_marq = new javax.swing.JComboBox();
        cmb_mod = new javax.swing.JComboBox();
        cmb_cate = new javax.swing.JComboBox();
        cmb_coul = new javax.swing.JComboBox();
        rbtn_ess = new javax.swing.JRadioButton();
        rbtn_gas = new javax.swing.JRadioButton();
        rbtn_gpl = new javax.swing.JRadioButton();
        txt_imma = new javax.swing.JTextField();
        txt_nbr_plac = new javax.swing.JTextField();
        txt_puiss = new javax.swing.JTextField();
        txt_num_chass = new javax.swing.JTextField();
        txt_cod_rad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_delai_deb = new com.toedter.calendar.JDateChooser();
        txt_delai_fin = new com.toedter.calendar.JDateChooser();
        date_circul = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(244, 243, 243));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/AjoutVoiture.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Gestion du véhicule");

        jPanel2.setBackground(new java.awt.Color(244, 243, 243));

        jPanel6.setBackground(new java.awt.Color(244, 243, 243));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNouv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNouv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/nouveau.png"))); // NOI18N
        btnNouv.setText("Nouveau");
        btnNouv.setOpaque(false);
        btnNouv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouvActionPerformed(evt);
            }
        });

        btnAjout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAjout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/ENGR.png"))); // NOI18N
        btnAjout.setText("Enregistrer");
        btnAjout.setOpaque(false);
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/supprimer.png"))); // NOI18N
        btnSupp.setText("Supprimer");
        btnSupp.setEnabled(false);
        btnSupp.setFocusPainted(false);
        btnSupp.setOpaque(false);
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnImp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackMenuForm/Icons/Imprimer.png"))); // NOI18N
        btnImp.setText("Imprimer");
        btnImp.setEnabled(false);
        btnImp.setFocusPainted(false);
        btnImp.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(btnNouv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnNouv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnImp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Les informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Immatriculation *");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Marque *");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Modèle *");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Nombre de place *");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Puissance");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Date de circulation");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Lieu de stationnement *");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("N° chassis");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Code radio");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Catégorie *");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Carburant *");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Couleur *");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Délai d'exploitation");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 255));
        jLabel16.setText("Début");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("Fin");

        cmb_lieu_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agence A", "Agence B", "Agence X", "Agence Y" }));

        cmb_marq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfa Remeo", "Audi", "Aston Martin", "BMW", "Cadillac", "Chevrolet", "Dacia", "Corvette", "Ford", "Hyundai", "Lamborghini", "Land Rover", "Mercedes", "Mini", "Renault", "Peugeot" }));
        cmb_marq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_marqItemStateChanged(evt);
            }
        });
        cmb_marq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_marqActionPerformed(evt);
            }
        });

        cmb_mod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_modItemStateChanged(evt);
            }
        });

        cmb_cate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tourisme", "Monospace" }));
        cmb_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cateActionPerformed(evt);
            }
        });

        cmb_coul.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abricot", "Absinthe", "Acajou", "Aigue-marine", "Aile de corbeau (cheveux)", "Albâtre", "Alezan (chevaux)", "Amande", "Amarante", "Ambre jaune", "Ambre rouge", "Améthyste", "Anthracite", "Aquilain (chevaux)", "Ardoise", "Argent", "Argent (héraldique)4", "Argile", "Asperge", "Aubergine", "Auburn (cheveux)", "Aurore", "Avocat", "Azur", "Azur (héraldique)", "Azur brume", "Azur clair", "Azurin", "Baillet (chevaux vieilli)", "Banane", "Basané (teint)", "Beige", "Beige clair", "Beigeasse (péjoratif)", "Beurre", "Beurre frais", "Bis", "Bis (héraldique)", "Bisque", "Bistre", "Bitume (pigment)", "Blanc", "Blanc cassé", "Blanc d'argent (pigment) ou de plomb", "Blanc d'Espagne (pigment)", "Blanc de lait", "Blanc de Meudon ou de Troyes (pigment)", "Blanc de zinc (pigment)", "Blanc lunaire", "Blé", "Bleu acier", "Bleu barbeau ou bleuet", "Bleu canard", "Bleu céleste", "Bleu charrette", "Bleu ciel", "Bleu de cobalt (pigment)", "Bleu de minuit", "Bleu de Prusse (pigment), de Berlin ou bleu hussard", "Bleu des mers du sud", "Bleu dragée", "Bleu électrique", "Bleu fumée", "Bleu givré", "Bleu guède (pigment)", "Bleu Klein &tm;", "Bleu Majorelle", "Bleu nuit", "Bleu outremer", "Bleu paon", "Bleu Persan", "Bleu pétrole", "Bleu", "Bleu roi ou de France", "Bleu turquin", "Blond vénitien (cheveux)", "Blond (cheveux)", "Bordeaux", "Bourgogne", "Bouton d'or", "Brique", "Bronze", "Brou de noix", "Brun (cheveux)", "Brun clair (cheveux)", "Bureau", "Caca d'oie", "Cacao", "Cachou (pigments)", "Cæruléum", "Café", "Café au lait", "Cannelle", "Capucine", "Caramel (pigments)", "Carmin (pigment)", "Carotte", "Cerise", "Cerise Hollywood", "Cerise profonde", "Cerise rose", "Céruse (pigment)", "Chair", "Chamois", "Chartreuse", "Châtaigne", "Châtain (cheveux)", "Chaudron", "Chocolat", "Cinabre (pigment)", "Citron", "Citrouille", "Colombin (vieilli)", "Coquelicot", "Coquille d'œuf", "Corail", "Cramoisi", "Crème", "Cuisse de nymphe", "Cuisse de nymphe émue", "Cuivre", "Cyan", "Denim", "Ébène", "Écarlate", "Écru", "Émeraude", "Étain", "Fauve", "Feu", "Feuille morte", "Flave", "Fraise", "Fraise écrasée", "Framboise", "Framboise rose", "Fuchsia", "Garance (pigment)", "Glauque", "Glycine", "Grège", "Grenadine", "Grenat", "Gris", "Gris acier", "Gris de lin", "Gris de Payne (mélange de pigments)", "Gris fer", "Gris perle", "Groseille", "Gueules (héraldique)", "Héliotrope", "Incarnadin", "Incarnat", "Indigo chaud", "Indigo du web", "Indigo électrique", "Indigo (teinture)", "Isabelle (chevaux)", "Ivoire", "Jais", "Jaune de cobalt ou auréolin (pigment)", "Jaune bouton d’or", "Jaune canari", "Jaune chartreuse", "Jaune d'or", "Jaune de Mars (pigment)", "Jaune de Naples (pigment)", "Jaune impérial", "Jaune mimosa", "Kaki", "Lapis-lazuli", "Lavallière (reliure)", "Lavande", "Lie de vin", "Lilas", "Lin", "Magenta fuchsia (encre)", "Magenta", "Magenta foncé, primaire en synthèse soustractive", "Maïs", "Malachite", "Mandarine", "Marine", "Marron", "Mastic", "Mauve (couleur)", "Melon", "Menthe", "Menthe à l'eau", "Mordoré", "Moutarde", "Nacarat", "Nankin", "Neige", "Noir", "Noir animal (pigment)", "Noir d'aniline (pigment)", "Noir d'encre", "Noir d'ivoire (pigment)", "Noir de carbone (pigment)", "Noir de fumée (pigment)", "Noir de jais", "Noisette", "Ocre jaune (pigment)", "Ocre rouge (pigment)", "Olive", "Opale", "Or", "Orange", "Orange brûlé", "Orchidée", "Orpiment (pigment)", "Orpin de Perse", "Paille", "Parme", "Pastel (pigment)", "Pelure d'oignon (œnologie)", "Pervenche", "Pistache", "Poil de chameau", "Ponceau", "Pourpre (héraldique)", "Prasin", "Prune", "Puce", "Queue-de-renard", "Rose", "Rose bonbon", "Rose dragée", "Rose du web", "Rose Mountbatten", "Rose Persan vif", "Rose razzle dazzle", "Rose shocking &tm;", "Rose ultra", "Rose vif", "Rouge-orangé sRGB", "Rouge anglais (pigment)", "Rouge cardinal", "Rouge cerise", "Rouge d'alizarine (pigment)", "Rouge d'Andrinople (pigment)", "Rouge de Falun (pigment)", "Rouge feu", "Rouge sang", "Rouge tomette", "Rouge turc (pigment)", "Rouille", "Roux", "Rubis", "Sable", "Sable (héraldique)", "Safran", "Safre", "Sang de bœuf", "Sanguine", "Saphir", "Sarcelle", "Saumon", "Saumon rose", "Sépia (pigment)", "Sinople (héraldique)", "Smalt (pigment)", "Smaragdin (pigment)", "Soufre", "Souris", "Tabac", "Tangerine (couleur)", "Taupe", "Terre d'ombre (pigment)", "Terre de Sienne (pigment)", "Terre de Sienne brûlée (pigment)", "Tomate", "Topaze", "Tourterelle", "Turquoise", "Vanille", "Vermeil", "Vermillon", "Vert", "Vert anis", "Vert bouteille", "Vert céladon", "Vert chartreuse", "Vert d'eau", "Vert de chrome ou anglais (pigment)", "Vert-de-gris (pigment)", "Vert de Hooker (mélange de pigments)", "Vert de vessie (pigment)", "Vert épinard", "Vert gazon ou herbe", "Vert impérial", "Vert kaki", "Vert lichen", "Vert lime", "Vert mélèze", "Vert militaire", "Vert mousse", "Vert opaline", "Vert perroquet", "Vert pin", "Vert poireau", "Vert pomme", "Vert prairie", "Vert printemps", "Vert sapin", "Vert sauge", "Vert tilleul", "Vert Véronèse (pigment)", "Violet", "Violet d'évêque", "Violine", "Viride (pigment)", "Zinzolin" }));

        rbtn_ess.setBackground(new java.awt.Color(255, 255, 255));
        rbtn_ess.setText("Essence");

        rbtn_gas.setBackground(new java.awt.Color(255, 255, 255));
        rbtn_gas.setText("Gasoil");

        rbtn_gpl.setBackground(new java.awt.Color(255, 255, 255));
        rbtn_gpl.setText("GPL");

        txt_nbr_plac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nbr_placActionPerformed(evt);
            }
        });

        txt_puiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puissActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("CV");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("Les champs avec (*) sont obligatoires");

        txt_delai_deb.setBackground(new java.awt.Color(244, 243, 243));

        txt_delai_fin.setBackground(new java.awt.Color(244, 243, 243));

        date_circul.setBackground(new java.awt.Color(244, 243, 243));
        date_circul.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmb_marq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_lieu_stat, 0, 151, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_puiss, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(txt_nbr_plac))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18))
                            .addComponent(date_circul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn_ess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_gas)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_gpl)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_coul, 0, 1, Short.MAX_VALUE)
                                .addGap(124, 124, 124))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmb_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_cod_rad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_num_chass)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_delai_deb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_delai_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_imma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txt_num_chass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_marq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txt_cod_rad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_nbr_plac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(rbtn_ess)
                            .addComponent(rbtn_gas)
                            .addComponent(rbtn_gpl))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_puiss, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(cmb_coul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(cmb_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(txt_delai_deb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_circul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(txt_delai_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_lieu_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouvActionPerformed
        // TODO add your handling code here:
          actualiser();
    }//GEN-LAST:event_btnNouvActionPerformed

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        
        if(txt_imma.getText().equals("") || cmb_marq.getSelectedItem().equals("") || cmb_mod.getSelectedItem().equals("") || txt_nbr_plac.getText().equals("")  
            || cmb_lieu_stat.getSelectedItem().equals("") || cmb_cate.getSelectedItem().equals("") || cmb_coul.getSelectedItem().equals("")){

            JOptionPane.showMessageDialog(this, "SVP les champs avec (*) sont obligatoires ");
        }else {
            
            String rbtn, delaiD, delaiF, dateCircul;
            delaiD = txt_delai_deb.getDate().toString();
            delaiF = txt_delai_fin.getDate().toString();
            dateCircul = date_circul.getDate().toString();
            if(rbtn_ess.isSelected()){
                rbtn ="Essence";
            }else if(rbtn_gas.isSelected()){
                rbtn ="Gasoil";
            }else{
                rbtn ="GPL";
            }
            String[] col = {"immatricule", "Marque", "Modele", "Nombre_Place", "Puissance", "Date_circulation", "Lieu_stationnement", "Num_chassis", "Code_radio", "Categorie", "Curburant", "Couleur", "Delai_debut", "Delai_fin"};
            String[] inf = {txt_imma.getText(), cmb_marq.getSelectedItem().toString(), cmb_mod.getSelectedItem().toString(),
                txt_nbr_plac.getText(), txt_puiss.getText(), dateCircul,cmb_lieu_stat.getSelectedItem().toString() ,
                txt_num_chass.getText(), txt_cod_rad.getText(), cmb_cate.getSelectedItem().toString(),
                rbtn, cmb_coul.getSelectedItem().toString(), delaiD, delaiF};
            try{
                System.out.println(db.queryInsert("g_client_vehi", col, inf));
                JOptionPane.showMessageDialog(this, "Enregistrer avec succée ");
            }catch(Exception e){
                System.out.println(e.getMessage());
                System.out.println("L ajoute du client n est pas valider");
            }
        }
    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppActionPerformed

    private void cmb_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cateActionPerformed

    private void txt_nbr_placActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nbr_placActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nbr_placActionPerformed

    private void txt_puissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puissActionPerformed

    private void cmb_marqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_marqItemStateChanged
        // TODO add your handling code here:
        InsertCmbModele();
    }//GEN-LAST:event_cmb_marqItemStateChanged

    private void cmb_marqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_marqActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_marqActionPerformed

    private void cmb_modItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_modItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_modItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnImp;
    private javax.swing.JButton btnNouv;
    private javax.swing.JButton btnSupp;
    private javax.swing.JComboBox cmb_cate;
    private javax.swing.JComboBox cmb_coul;
    private javax.swing.JComboBox cmb_lieu_stat;
    private javax.swing.JComboBox cmb_marq;
    private javax.swing.JComboBox cmb_mod;
    private com.toedter.calendar.JDateChooser date_circul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbtn_ess;
    private javax.swing.JRadioButton rbtn_gas;
    private javax.swing.JRadioButton rbtn_gpl;
    private javax.swing.JTextField txt_cod_rad;
    private com.toedter.calendar.JDateChooser txt_delai_deb;
    private com.toedter.calendar.JDateChooser txt_delai_fin;
    private javax.swing.JTextField txt_imma;
    private javax.swing.JTextField txt_nbr_plac;
    private javax.swing.JTextField txt_num_chass;
    private javax.swing.JTextField txt_puiss;
    // End of variables declaration//GEN-END:variables
}
